### ISSUE TITLE
The video is private QwQ.

### ISSUE THREAD

**Issue by saisesai** [codingminecraft/FontRendering#1]
Hey Gabe, the link to your latest video is private, we can't play it.
Your tutorials are awsome, and I am coding your 2D game engine series in cpp recently :D.
https://github.com/saisesai/mario-cpp

**Comment by codingminecraft** [comment]
Hi Shiro! Yea, I scheduled it for 9:15 this morning CST. YouTube usually
takes some time to process the HD version of the video so I'll generally
schedule them for the next day. It should be released in 30 minutes though,
thanks for letting me know though!

Regards,
Gabe
